### ISSUE TITLE
SDMM can miss relative type definitions if a space is used

### ISSUE THREAD

**Issue by Zandario** [SpaceManiac/SpacemanDMM#351]
## Details
First noticed this while making our codebase compatible with OpenDream.
https://github.com/Citadel-Station-13/Citadel-Station-13-RP/blob/master/code/game/objects/items/stacks/sandbag.dm#L52

From what I've tested, this only happens to types, procs will error for other reasons to prevent this.

## Reproduction
![image](https://user-images.githubusercontent.com/34761877/224441012-b35bcc69-6fcc-4686-82ba-41db203d648b.png)

<details>
<summary>Copyable Reproduction</summary>

### test.dm
```dm
/atom
	foo
		name = "Test"

/atom
	bar name = "Test"
```

### SpacemanDMM.toml
```toml
[langserver]
dreamchecker = true

[code_standards]
disallow_relative_type_definitions = true
```
</details>
